Add files via upload
Most recent error shown in terminal:

Tweet sent!
{'date': 20231202, 'id': 968270, 'competition': 'Premier League', 'home team': 'Newcastle United', 'away team': 'Manchester United', 'home score': 0, 'away score': 0, 'minute': 0, 'team': 0, 'player': 0, 'event': 0, 'status': 0}
Tweet sent!
{'date': 20231202, 'id': 968270, 'competition': 'Premier League', 'home team': 'Newcastle United', 'away team': 'Manchester United', 'home score': 1, 'away score': 0, 'minute': 55, 'team': 'Newcastle United', 'player': 'Anthony Gordon', 'event': 'Goal', 'status': 0}
Traceback (most recent call last):
  File "C:\Users\rchar\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "C:\Users\rchar\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_backends\sync.py", line 206, in connect_tcp
    sock = socket.create_connection(
  File "C:\Users\rchar\AppData\Local\Programs\Python\Python310\lib\socket.py", line 845, in create_connection
    raise err
  File "C:\Users\rchar\AppData\Local\Programs\Python\Python310\lib\socket.py", line 833, in create_connection
    sock.connect(sa)
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\rchar\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_transports\default.py", line 66, in map_httpcore_exceptions
    yield
  File "C:\Users\rchar\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_transports\default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
  File "C:\Users\rchar\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_sync\connection_pool.py", line 268, in handle_request
    raise exc
  File "C:\Users\rchar\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_sync\connection_pool.py", line 251, in handle_request
    response = connection.handle_request(request)
  File "C:\Users\rchar\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_sync\connection.py", line 99, in handle_request
    raise exc
  File "C:\Users\rchar\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_sync\connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "C:\Users\rchar\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_sync\connection.py", line 124, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "C:\Users\rchar\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_backends\sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "C:\Users\rchar\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\rchar\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectTimeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\rchar\OneDrive\Documents\orca_source\bayern-munich-bot-main\bayern-munich-bot-main\main.py", line 146, in <module>
    schedule.run_pending()
  File "C:\Users\rchar\AppData\Local\Programs\Python\Python310\lib\site-packages\schedule\__init__.py", line 822, in run_pending
    default_scheduler.run_pending()
  File "C:\Users\rchar\AppData\Local\Programs\Python\Python310\lib\site-packages\schedule\__init__.py", line 100, in run_pending
    self._run_job(job)
  File "C:\Users\rchar\AppData\Local\Programs\Python\Python310\lib\site-packages\schedule\__init__.py", line 172, in _run_job
    ret = job.run()
  File "C:\Users\rchar\AppData\Local\Programs\Python\Python310\lib\site-packages\schedule\__init__.py", line 693, in run
    ret = self.job_func()
  File "c:\Users\rchar\OneDrive\Documents\orca_source\bayern-munich-bot-main\bayern-munich-bot-main\main.py", line 94, in tweet
    match_events = livescore.getGameInPlay(todays_id)
  File "c:\Users\rchar\OneDrive\Documents\orca_source\bayern-munich-bot-main\bayern-munich-bot-main\LiveScore.py", line 116, in getGameInPlay
    response = httpx.get(f'https://prod-public-api.livescore.com/v1/api/app/scoreboard/soccer/{id}?locale=en')
  File "C:\Users\rchar\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_api.py", line 189, in get
    return request(
  File "C:\Users\rchar\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_api.py", line 100, in request
    return client.request(
  File "C:\Users\rchar\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_client.py", line 814, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "C:\Users\rchar\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_client.py", line 901, in send
    response = self._send_handling_auth(
  File "C:\Users\rchar\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
  File "C:\Users\rchar\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
  File "C:\Users\rchar\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
  File "C:\Users\rchar\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_transports\default.py", line 227, in handle_request
    with map_httpcore_exceptions():
  File "C:\Users\rchar\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\rchar\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_transports\default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout: timed out

[Done] exited with code=1 in 152.78 seconds